name: Build site on schedule or main branch update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "* */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: Keep actions alive
          committer_username: nrayamajhee
          committer_email: nishan@rayamajhee.com
  deploy:
      needs: build
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
            
